# Generated by Django 5.2.8 on 2025-12-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0007_alter_group_id_alter_groupinvite_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="group_type",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public"),
                    ("RESTRICTED", "Restricted"),
                    ("PRIVATE", "Private"),
                ],
                default="PUBLIC",
                help_text="PUBLIC: Anyone can view, post, and comment to this community.<br>RESTRICTED: Anyone can view this community, but only approved users can post.<br>PRIVATE: Only approved users can view and submit to this community.",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="member_type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("MODERATOR", "Moderator"),
                    ("MEMBER", "Member"),
                ],
                default="MEMBER",
                help_text="ADMIN: Has (all)permissions to add or remove members as moderators, ban or mute members.<br>MODERATOR: Has permission to add, remove, ban or mute members.<br>MEMBER: Can post, like, comment, share, bookmark group posts.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("BANNED", "Banned"),
                    ("MUTED", "Muted"),
                ],
                default="ACTIVE",
                help_text="ACTIVE: Can be active in a group within permissions.<br>MUTED: Forbidden for any activity(post, comment etc) in a group for a week.<br>BANNED: Forbidden for any activity in a group forever",
                max_length=10,
            ),
        ),
    ]
